#!/bin/bash

set -e

export ANDROID_HOME="/opt/android-sdk"
export ANDROID_NDK_HOME="${ANDROID_HOME}/ndk-bundle"

export GOROOT="/opt/go"
export GOBIN="$GOROOT/bin"
export GOPATH="/root/go"
export GO111MODULE=off
export GOPROXY=direct

export PATH=${PATH}:${GOBIN}:${GOPATH}/bin:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools

# change dir
cd ${GOPATH}/src/AndroidLibXrayLite

download_data=0
update_go_dep=0

for param in "$@"; do
  case $param in
  data*)
    download_data=1
    ;;
  dep*)
    update_go_dep=1
    ;;
  esac
done

echo "Update go dep......"
if [[ ${update_go_dep} == "1" ]] ; then
  # download dep
  go get -u github.com/golang/protobuf/protoc-gen-go/...
  go get -u golang.org/x/mobile/cmd/...
  go get -u github.com/jteeuwen/go-bindata/...
  
  go get -u github.com/ghodss/yaml/...
  go get -u github.com/gorilla/websocket/...
  go get -u github.com/lucas-clemente/quic-go/...
  go get -u github.com/pelletier/go-toml/...
  go get -u github.com/refraction-networking/utls/...
  go get -u github.com/seiflotfy/cuckoofilter/...
  go get -u github.com/xtls/go/...
  go get -u go.starlark.net/starlark/...
  go get -u go.starlark.net/syntax/...
  go get -u golang.org/x/crypto/chacha20poly1305/...
  go get -u golang.org/x/crypto/hkdf/...
  go get -u golang.org/x/crypto/ocsp/...
  go get -u golang.org/x/crypto/sha3/...
  go get -u golang.org/x/net/dns/dnsmessage/...
  go get -u golang.org/x/net/http2/...
  go get -u golang.org/x/net/http2/h2c/...
  go get -u google.golang.org/grpc/...
  go get -u google.golang.org/grpc/backoff/...
  go get -u google.golang.org/grpc/codes/...
  go get -u google.golang.org/grpc/connectivity/...
  go get -u google.golang.org/grpc/credentials/...
  go get -u google.golang.org/grpc/peer/...
  go get -u google.golang.org/grpc/reflection/...
  go get -u google.golang.org/grpc/status/...
  
  go get -u github.com/xtls/xray-core/core/...

  #go get AndroidLibXrayLite
fi


if [[ ${download_data} == "1" ]] ; then
  echo "Download geo data....."
  /bin/bash gen_assets.sh download
fi

cd shippedBinarys && make shippedBinary && cd ..

echo "compile aar"
gomobile init && gomobile bind -v  -tags json .
